require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppraiserAccessTokensController do

  # This should return the minimal set of attributes required to create a valid
  # AppraiserAccessToken. As you add validations to AppraiserAccessToken, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppraiserAccessTokensController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all appraiser_access_tokens as @appraiser_access_tokens" do
      appraiser_access_token = AppraiserAccessToken.create! valid_attributes
      get :index, {}, valid_session
      assigns(:appraiser_access_tokens).should eq([appraiser_access_token])
    end
  end

  describe "GET show" do
    it "assigns the requested appraiser_access_token as @appraiser_access_token" do
      appraiser_access_token = AppraiserAccessToken.create! valid_attributes
      get :show, {:id => appraiser_access_token.to_param}, valid_session
      assigns(:appraiser_access_token).should eq(appraiser_access_token)
    end
  end

  describe "GET new" do
    it "assigns a new appraiser_access_token as @appraiser_access_token" do
      get :new, {}, valid_session
      assigns(:appraiser_access_token).should be_a_new(AppraiserAccessToken)
    end
  end

  describe "GET edit" do
    it "assigns the requested appraiser_access_token as @appraiser_access_token" do
      appraiser_access_token = AppraiserAccessToken.create! valid_attributes
      get :edit, {:id => appraiser_access_token.to_param}, valid_session
      assigns(:appraiser_access_token).should eq(appraiser_access_token)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppraiserAccessToken" do
        expect {
          post :create, {:appraiser_access_token => valid_attributes}, valid_session
        }.to change(AppraiserAccessToken, :count).by(1)
      end

      it "assigns a newly created appraiser_access_token as @appraiser_access_token" do
        post :create, {:appraiser_access_token => valid_attributes}, valid_session
        assigns(:appraiser_access_token).should be_a(AppraiserAccessToken)
        assigns(:appraiser_access_token).should be_persisted
      end

      it "redirects to the created appraiser_access_token" do
        post :create, {:appraiser_access_token => valid_attributes}, valid_session
        response.should redirect_to(AppraiserAccessToken.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved appraiser_access_token as @appraiser_access_token" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppraiserAccessToken.any_instance.stub(:save).and_return(false)
        post :create, {:appraiser_access_token => {}}, valid_session
        assigns(:appraiser_access_token).should be_a_new(AppraiserAccessToken)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppraiserAccessToken.any_instance.stub(:save).and_return(false)
        post :create, {:appraiser_access_token => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested appraiser_access_token" do
        appraiser_access_token = AppraiserAccessToken.create! valid_attributes
        # Assuming there are no other appraiser_access_tokens in the database, this
        # specifies that the AppraiserAccessToken created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AppraiserAccessToken.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => appraiser_access_token.to_param, :appraiser_access_token => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested appraiser_access_token as @appraiser_access_token" do
        appraiser_access_token = AppraiserAccessToken.create! valid_attributes
        put :update, {:id => appraiser_access_token.to_param, :appraiser_access_token => valid_attributes}, valid_session
        assigns(:appraiser_access_token).should eq(appraiser_access_token)
      end

      it "redirects to the appraiser_access_token" do
        appraiser_access_token = AppraiserAccessToken.create! valid_attributes
        put :update, {:id => appraiser_access_token.to_param, :appraiser_access_token => valid_attributes}, valid_session
        response.should redirect_to(appraiser_access_token)
      end
    end

    describe "with invalid params" do
      it "assigns the appraiser_access_token as @appraiser_access_token" do
        appraiser_access_token = AppraiserAccessToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppraiserAccessToken.any_instance.stub(:save).and_return(false)
        put :update, {:id => appraiser_access_token.to_param, :appraiser_access_token => {}}, valid_session
        assigns(:appraiser_access_token).should eq(appraiser_access_token)
      end

      it "re-renders the 'edit' template" do
        appraiser_access_token = AppraiserAccessToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppraiserAccessToken.any_instance.stub(:save).and_return(false)
        put :update, {:id => appraiser_access_token.to_param, :appraiser_access_token => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested appraiser_access_token" do
      appraiser_access_token = AppraiserAccessToken.create! valid_attributes
      expect {
        delete :destroy, {:id => appraiser_access_token.to_param}, valid_session
      }.to change(AppraiserAccessToken, :count).by(-1)
    end

    it "redirects to the appraiser_access_tokens list" do
      appraiser_access_token = AppraiserAccessToken.create! valid_attributes
      delete :destroy, {:id => appraiser_access_token.to_param}, valid_session
      response.should redirect_to(appraiser_access_tokens_url)
    end
  end

end
