require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TradeReferencesController do

  # This should return the minimal set of attributes required to create a valid
  # TradeReference. As you add validations to TradeReference, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TradeReferencesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trade_references as @trade_references" do
      trade_reference = TradeReference.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trade_references).should eq([trade_reference])
    end
  end

  describe "GET show" do
    it "assigns the requested trade_reference as @trade_reference" do
      trade_reference = TradeReference.create! valid_attributes
      get :show, {:id => trade_reference.to_param}, valid_session
      assigns(:trade_reference).should eq(trade_reference)
    end
  end

  describe "GET new" do
    it "assigns a new trade_reference as @trade_reference" do
      get :new, {}, valid_session
      assigns(:trade_reference).should be_a_new(TradeReference)
    end
  end

  describe "GET edit" do
    it "assigns the requested trade_reference as @trade_reference" do
      trade_reference = TradeReference.create! valid_attributes
      get :edit, {:id => trade_reference.to_param}, valid_session
      assigns(:trade_reference).should eq(trade_reference)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TradeReference" do
        expect {
          post :create, {:trade_reference => valid_attributes}, valid_session
        }.to change(TradeReference, :count).by(1)
      end

      it "assigns a newly created trade_reference as @trade_reference" do
        post :create, {:trade_reference => valid_attributes}, valid_session
        assigns(:trade_reference).should be_a(TradeReference)
        assigns(:trade_reference).should be_persisted
      end

      it "redirects to the created trade_reference" do
        post :create, {:trade_reference => valid_attributes}, valid_session
        response.should redirect_to(TradeReference.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trade_reference as @trade_reference" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeReference.any_instance.stub(:save).and_return(false)
        post :create, {:trade_reference => {}}, valid_session
        assigns(:trade_reference).should be_a_new(TradeReference)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeReference.any_instance.stub(:save).and_return(false)
        post :create, {:trade_reference => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trade_reference" do
        trade_reference = TradeReference.create! valid_attributes
        # Assuming there are no other trade_references in the database, this
        # specifies that the TradeReference created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TradeReference.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => trade_reference.to_param, :trade_reference => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested trade_reference as @trade_reference" do
        trade_reference = TradeReference.create! valid_attributes
        put :update, {:id => trade_reference.to_param, :trade_reference => valid_attributes}, valid_session
        assigns(:trade_reference).should eq(trade_reference)
      end

      it "redirects to the trade_reference" do
        trade_reference = TradeReference.create! valid_attributes
        put :update, {:id => trade_reference.to_param, :trade_reference => valid_attributes}, valid_session
        response.should redirect_to(trade_reference)
      end
    end

    describe "with invalid params" do
      it "assigns the trade_reference as @trade_reference" do
        trade_reference = TradeReference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeReference.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_reference.to_param, :trade_reference => {}}, valid_session
        assigns(:trade_reference).should eq(trade_reference)
      end

      it "re-renders the 'edit' template" do
        trade_reference = TradeReference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeReference.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_reference.to_param, :trade_reference => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trade_reference" do
      trade_reference = TradeReference.create! valid_attributes
      expect {
        delete :destroy, {:id => trade_reference.to_param}, valid_session
      }.to change(TradeReference, :count).by(-1)
    end

    it "redirects to the trade_references list" do
      trade_reference = TradeReference.create! valid_attributes
      delete :destroy, {:id => trade_reference.to_param}, valid_session
      response.should redirect_to(trade_references_url)
    end
  end

end
